.TH "matrix" 3 "tstform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix \- массив значений зон экрана  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBButtons\fP [16]"
.br
.ti -1c
.RI "int \fBrow_col\fP [4][4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
массив значений зон экрана 
.PP
Definition at line \fB15\fP of file \fBfiveteen\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "int Buttons[16]"

.PP
Definition at line \fB16\fP of file \fBfiveteen\&.c\fP\&.
.SS "int row_col[4][4]"

.PP
Definition at line \fB17\fP of file \fBfiveteen\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for tstform from the source code\&.
